## Market Basket Analysis Introduction

Companion notebook to http://pbpython.com/market-basket-analysis.html

![alt text](http://pbpython.com/images/market-basket.png)

In [1]:
# Required library
!pip install mlxtend
!pip install xlrd

Requirement already satisfied: mlxtend in /usr/local/lib/python3.6/dist-packages (0.14.0)
Requirement already satisfied: pandas>=0.17.1 in /usr/local/lib/python3.6/dist-packages (from mlxtend) (0.25.3)
Requirement already satisfied: scikit-learn>=0.18 in /usr/local/lib/python3.6/dist-packages (from mlxtend) (0.22.2.post1)
Requirement already satisfied: setuptools in /usr/local/lib/python3.6/dist-packages (from mlxtend) (45.2.0)
Requirement already satisfied: matplotlib>=1.5.1 in /usr/local/lib/python3.6/dist-packages (from mlxtend) (3.2.0)
Requirement already satisfied: scipy>=0.17 in /usr/local/lib/python3.6/dist-packages (from mlxtend) (1.4.1)
Requirement already satisfied: numpy>=1.10.4 in /usr/local/lib/python3.6/dist-packages (from mlxtend) (1.18.1)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.6/dist-packages (from pandas>=0.17.1->mlxtend) (2018.9)
Requirement already satisfied: python-dateutil>=2.6.1 in /usr/local/lib/python3.6/dist-packages (from pandas>=0.17.1->mlxtend) (2.8.1)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.6/dist-packages (from scikit-learn>=0.18->mlxtend) (0.14.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib>=1.5.1->mlxtend) (1.1.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.6/dist-packages (from matplotlib>=1.5.1->mlxtend) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib>=1.5.1->mlxtend) (2.4.6)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.6/dist-packages (from python-dateutil>=2.6.1->pandas>=0.17.1->mlxtend) (1.12.0)
Requirement already satisfied: xlrd in /usr/local/lib/python3.6/dist-packages (1.1.0)

In [0]:
import pandas as pd
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [0]:
df = pd.read_excel('https://github.com/davidjohnnn/all_datasets/raw/master/bay/Online_Retail.xlsx')

In [4]:
df.head()

  InvoiceNo StockCode  ... CustomerID         Country
0    536365    85123A  ...    17850.0  United Kingdom
1    536365     71053  ...    17850.0  United Kingdom
2    536365    84406B  ...    17850.0  United Kingdom
3    536365    84029G  ...    17850.0  United Kingdom
4    536365    84029E  ...    17850.0  United Kingdom

[5 rows x 8 columns]

In [0]:
# Clean up spaces in description and remove any rows that don't have a valid invoice
df['Description'] = df['Description'].str.strip()
df.dropna(axis=0, subset=['InvoiceNo'], inplace=True)

In [0]:
# Remove the credit transactions (those with invoice numbers containing C)
df['InvoiceNo'] = df['InvoiceNo'].astype('str')
df = df[~df['InvoiceNo'].str.contains('C')]

## Association Rules for France

In [0]:
# Only looking at sales for France. However, in additional code below, I will compare these results to sales from Germany
basket = (df[df['Country'] =="France"]
          .groupby(['InvoiceNo', 'Description'])['Quantity']
          .sum().unstack().reset_index().fillna(0)
          .set_index('InvoiceNo'))

In [8]:
basket.head()

Description  10 COLOUR SPACEBOY PEN  ...  ZINC T-LIGHT HOLDER STARS SMALL
InvoiceNo                            ...
536370                          0.0  ...                              0.0
536852                          0.0  ...                              0.0
536974                          0.0  ...                              0.0
537065                          0.0  ...                              0.0
537463                          0.0  ...                              0.0

[5 rows x 1563 columns]

In [9]:
# Show a subset of columns
basket.iloc[:,[0,1,2,3,4,5,6, 7]].head()

Description  10 COLOUR SPACEBOY PEN  ...  12 PENCILS TALL TUBE POSY
InvoiceNo                            ...
536370                          0.0  ...                        0.0
536852                          0.0  ...                        0.0
536974                          0.0  ...                        0.0
537065                          0.0  ...                        0.0
537463                          0.0  ...                        0.0

[5 rows x 8 columns]

In [0]:
# There are a lot of zeros in the data but we also need to make sure any positive values are converted to a 1 and anything less the 0 is set to 0.

# Convert the units to 1 hot encoded values
def encode_units(x):
    if x <= 0:
        return 0
    if x >= 1:
        return 1
      
# Convert to one hot vector
basket_sets = basket.applymap(encode_units)

In [0]:
# No need to track postage
# Remove column "Postage" (1 column)
basket_sets.drop('POSTAGE', inplace=True, axis=1)

In [12]:
basket_sets.head()

Description  10 COLOUR SPACEBOY PEN  ...  ZINC T-LIGHT HOLDER STARS SMALL
InvoiceNo                            ...
536370                            0  ...                                0
536852                            0  ...                                0
536974                            0  ...                                0
537065                            0  ...                                0
537463                            0  ...                                0

[5 rows x 1562 columns]

In [0]:
# Build up the frequent items
frequent_itemsets = apriori(basket_sets, min_support=0.07, use_colnames=True)

In [14]:
frequent_itemsets.head()

    support                        itemsets
0  0.071429   (4 TRADITIONAL SPINNING TOPS)
1  0.096939    (ALARM CLOCK BAKELIKE GREEN)
2  0.102041     (ALARM CLOCK BAKELIKE PINK)
3  0.094388      (ALARM CLOCK BAKELIKE RED)
4  0.081633  (BAKING SET 9 PIECE RETROSPOT)

In [15]:
# Create the rules
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1)
rules.head()

                    antecedents  ... conviction
0  (ALARM CLOCK BAKELIKE GREEN)  ...   3.791383
1   (ALARM CLOCK BAKELIKE PINK)  ...   3.283859
2    (ALARM CLOCK BAKELIKE RED)  ...   5.568878
3  (ALARM CLOCK BAKELIKE GREEN)  ...   4.916181
4    (ALARM CLOCK BAKELIKE RED)  ...   4.153061

[5 rows x 9 columns]

In [16]:
rules[ (rules['lift'] >= 6) &
       (rules['confidence'] >= 0.8) ]

                                          antecedents  ... conviction
2                          (ALARM CLOCK BAKELIKE RED)  ...   5.568878
3                        (ALARM CLOCK BAKELIKE GREEN)  ...   4.916181
17                    (SET/6 RED SPOTTY PAPER PLATES)  ...   4.336735
18                    (SET/6 RED SPOTTY PAPER PLATES)  ...  21.556122
19                      (SET/6 RED SPOTTY PAPER CUPS)  ...   7.852041
20  (SET/20 RED RETROSPOT PAPER NAPKINS, SET/6 RED...  ...  34.489796
21  (SET/20 RED RETROSPOT PAPER NAPKINS, SET/6 RED...  ...  34.897959
22  (SET/6 RED SPOTTY PAPER PLATES, SET/6 RED SPOT...  ...   4.625850

[8 rows x 9 columns]

In [17]:
basket['ALARM CLOCK BAKELIKE GREEN'].sum()

340.0

In [18]:
basket['ALARM CLOCK BAKELIKE RED'].sum()

316.0

In [0]:
# What is also interesting is to see how the combinations vary by country of purchase.
# Let’s check out what some popular combinations might be in Germany

## Association Rules for Germany

In [0]:
basket2 = (df[df['Country'] =="Germany"]
          .groupby(['InvoiceNo', 'Description'])['Quantity']
          .sum().unstack().reset_index().fillna(0)
          .set_index('InvoiceNo'))

In [0]:
# Convert to one hot vector
basket_sets2 = basket2.applymap(encode_units)

In [0]:
basket_sets2.drop('POSTAGE', inplace=True, axis=1)

In [0]:
frequent_itemsets2 = apriori(basket_sets2, min_support=0.05, use_colnames=True)

In [24]:
rules2 = association_rules(frequent_itemsets2, metric="lift", min_threshold=1)
rules2.head()

                           antecedents  ... conviction
0      (PLASTERS IN TIN CIRCUS PARADE)  ...   2.076984
1   (PLASTERS IN TIN WOODLAND ANIMALS)  ...   1.740427
2      (PLASTERS IN TIN CIRCUS PARADE)  ...   1.488330
3  (ROUND SNACK BOXES SET OF 4 FRUITS)  ...   1.298977
4      (PLASTERS IN TIN CIRCUS PARADE)  ...   1.481887

[5 rows x 9 columns]

In [25]:
rules2[ (rules2['lift'] >= 4) &
        (rules2['confidence'] >= 0.5) ]

                        antecedents  ... conviction
0   (PLASTERS IN TIN CIRCUS PARADE)  ...   2.076984
6        (PLASTERS IN TIN SPACEBOY)  ...   2.011670
11    (RED RETROSPOT CHARLOTTE BAG)  ...   5.587746

[3 rows x 9 columns]